# Site settings
title: Doug Forrest
description: 'Business Card Page'
url: 'https://dougforrest.github.io'
baseurl: '/biz_card'
profilepic: '/images/IMG_0782_400x.jpg'
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: '370533a5f8.js'
qr_code: '/images/qr.png'


author:
  name: 'Doug Forrest'
  email: DougForrest@gmail.com
  github_username:  dougforrest
  linkedin_username: doug-forrest-6808a850
  


# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
